meta_product_name: "GGBee "
meta_title: "Live Audience Stats for CBLoL"
meta_description: "GGBee is a service for collecting, organizing and analyzing data on the competitive LoL scenario in Brazil."
meta_image: "cover.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
